//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestHostes.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order_Meal
    {
        public int Id { get; set; }
        public Nullable<int> MealID { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
